services:
  postgres:
    image: kaiquemsilva/ac2-project-java:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ac2_project
    volumes:
      - db-volume:/var/lib/postgresql/data1

  api:
    image: kaiquemsilva/ac2-project-java:latest
    networks:
      - default
    environment:
      DB_HOST: postgres
    ports:
      - "8687:8080"

volumes:
  db-volume:
