services:
  postgres:
    image: ac2_project
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ac2_project
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: kaiquemsilva/ac2-project-java:latest
    networks:
      - default
    environment:
      DB_HOST: database
    ports:
      - "8686:8080"

volumes:
  db-volume:
